$(document).ready(function(){
    $(".itemOrder").hide();
    $("a").mouseenter(function(){
        $(this).next().slideDown();
    })
    $(".itemOrder").mouseleave(function(){
        $(".itemOrder").slideUp();
    })
})